### PR TITLE
Add detailed page titles

### PR DESCRIPTION
**Pull request by annavik**
Fixes https://github.com/RolnickLab/ami-platform/issues/196

We are basing the page titles on the current breadcrumbs, to be consistent. We just reverse them.

Example of some page titles after this update:

Screenshot 2023-10-23 at 16 58 37

### CODE REVIEW

**Comment by annavik** [comment]
We could easily be even more detailed here, for example include more information for all details views (not just sessions). Do you think that is a good idea or are titles starting to get too complex? @mihow

**Comment by mihow** [comment]
Thanks so much @annavik. I do think we should make titles specific to each detail page. Then it will be much easier to navigate through your history and it will be helpful when pasting links in Slack, etc. And it will be much better for search indexes when we go live.

For many detail pages the title could just use the object id "#341 | Occurrences | Vermont ML | AMI Platform". For projects, deployments & species you can use their nice names. Actually even occurrences could be "Actias Luna #241"

**Comment by annavik** [comment]
> Thanks so much @annavik. I do think we should make titles specific to each detail page. Then it will be much easier to navigate through your history and it will be helpful when pasting links in Slack, etc. And it will be much better for search indexes when we go live.
> 
> For many detail pages the title could just use the object id "#341 | Occurrences | Vermont ML | AMI Platform". For projects, deployments & species you can use their nice names. Actually even occurrences could be "Actias Luna #241"

Fixed! Added more specific titles for jobs, deployments, occurrences and species. Example:

Screenshot 2023-10-25 at 14 57 58

**Comment by annavik** [comment]
The update also affects detail breadcrumb, although most of the time it will not be visible behind dialog. If we decide to go from dialog -> full page for more detail views it could be nice to have though.

Screenshot 2023-10-25 at 15 01 02

**Comment by annavik** [comment]
@mihow I also included a small change to update description when a project is selected. Looks a bit nicer when we share links. From Slack:
Screenshot 2023-10-25 at 17 25 26

See #294

**Review by mihow — APPROVED** [review]
Love it! Thank you for adding the meta previews. We can add images eventually when we get thumbnailing working!

**Pull request merged**
